### ISSUE TITLE
Unsure what IP address and port to use in GA behavior box

### ISSUE THREAD

**Issue by anjalie-ch** [conema/ZAGA#5]
Ended up using the published port of docker container to connect to the TCP 4000 port, tried many variations of IP address and port value (4000 versus published port value)

[ERROR] behavior.box :_safeCallOfUserMethod:130 _Behavior__lastUploadedChoregrapheBehaviorbehavior_12715416512:/GA_7/GA_2: Traceback (most recent call last):   File "/opt/aldebaran/lib/python2.7/site-packages/albehavior.py", line 120, in _safeCallOfUserMethod     func()   File "<string>", line 69, in onInput_onStart   File "<string>", line 60, in start_zora   File "<string>", line 220, in connect_ga   File "/usr/lib/python2.7/socket.py", line 228, in meth     return getattr(self._sock,name)(*args) error: [Errno 111] Connection refused  
[INFO ] behavior.box :start_zora:58 _Behavior__lastUploadedChoregrapheBehaviorbehavior_12715416512:/GA_7/GA_2: Recording... 
[ERROR] behavior.box :_safeCallOfUserMethod:130 _Behavior__lastUploadedChoregrapheBehaviorbehavior_12715416512:/GA_7/GA_2: Traceback (most recent call last):   File "/opt/aldebaran/lib/python2.7/site-packages/albehavior.py", line 120, in _safeCallOfUserMethod     func()   File "<string>", line 44, in onUnload   File "/opt/aldebaran/lib/python2.7/site-packages/ialbehavior.py", line 166, in <lambda>     __getattr__ = lambda self, name: _swig_getattr(self, behavior, name)   File "/opt/aldebaran/lib/python2.7/site-packages/ialbehavior.py", line 74, in _swig_getattr     return _swig_getattr_nondynamic(self, class_type, name, 0)   File "/opt/aldebaran/lib/python2.7/site-packages/ialbehavior.py", line 69, in _swig_getattr_nondynamic     return object.__getattr__(self, name) AttributeError: type object 'object' has no attribute '__getattr__'

**Comment by conema** [comment]
If I remember well, you should use your local ip address, you can find it by using ipconfig/ifconfig. The port is correct.
