### ISSUE TITLE
Connection Timed out Error

### ISSUE THREAD

**Issue by tyler-lynch** [conema/ZAGA#6]
Hello again!

So I am getting an error when trying to run the Choreograph project and I was wondering if you had any insight in to where the error might be coming from. 

`[ERROR] behavior.box :_safeCallOfUserMethod:130 _Behavior__lastUploadedChoregrapheBehaviorbehavior_12595797312:/GA_7/GA_2: Traceback (most recent call last):   File "/opt/aldebaran/lib/python2.7/site-packages/albehavior.py", line 120, in _safeCallOfUserMethod     func()   File "<string>", line 44, in onUnload   File "/opt/aldebaran/lib/python2.7/site-packages/ialbehavior.py", line 108, in <lambda>     __getattr__ = lambda self, name: _swig_getattr(self, behavior, name)   File "/opt/aldebaran/lib/python2.7/site-packages/ialbehavior.py", line 57, in _swig_getattr     raise AttributeError(name) AttributeError: s  
[ERROR] behavior.box :_safeCallOfUserMethod:130 _Behavior__lastUploadedChoregrapheBehaviorbehavior_12595797312:/GA_7/GA_2: Traceback (most recent call last):   File "/opt/aldebaran/lib/python2.7/site-packages/albehavior.py", line 120, in _safeCallOfUserMethod     func()   File "<string>", line 69, in onInput_onStart   File "<string>", line 60, in start_zora   File "<string>", line 220, in connect_ga   File "/usr/lib/python2.7/socket.py", line 228, in meth     return getattr(self._sock,name)(*args) error: [Errno 110] Connection timed out  `

My guess is that it is an error with my Google Assistant, but I've trying reconfiguring it and I still end up with the same thing.

**Comment by conema** [comment]
Hi @tyler-lynch,
Did you [start the GA server](https://github.com/conema/ZAGA#usage-with-naozora) and set the correct ip/port?
